name: Deploy

on:
    push:
        tags:
            - "v*.*.*"
            - "v*.*.*-*"

env:
    CARGO_TERM_COLOR: always

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest

        steps:
            - id: checkout
              name: Checkout Repository
              uses: actions/checkout@v4

            - id: setup
              name: Setup Environment
              uses: actions/setup-node@v4

            - id: toolchain
              name: Setup Toolchain
              run: corepack enable

            - id: install
              name: Install Dependencies
              run: yarn install --no-immutable

            - id: publish
              name: Publish to Npm
              run: yarn npm publish --non-interactive
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
