name: Testing

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: setup
        name: Setup Environment
        uses: actions/setup-node@v4

      - id: toolchain
        name: Setup Toolchain
        run: corepack enable

      - id: install
        name: Install Dependencies
        run: yarn install --no-immutable

      - id: check
        name: Run Formatting-Checks
        run: yarn run format:check

      - id: lint
        name: Run Code Quality Checks
        run: yarn run lint

  unit:
    name: Units
    runs-on: ubuntu-latest
    needs: format

    steps:
      - id: checkout
        name: Checkout Repository
        uses: actions/checkout@v4

      - id: setup
        name: Setup Environment
        uses: actions/setup-node@v4

      - id: toolchain
        name: Setup Toolchain
        run: corepack enable

      - id: install
        name: Install Dependencies
        run: yarn install --no-immutable

      - id: check
        name: Build and Package
        run: yarn run build

      - id: lint
        name: Run Code Quality Checks
        run: yarn run test
